### ISSUE TITLE
FMUAnalyzer Text

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmi_utilities#10]
I would like some text presenting the FMU Analyzer at https://sweng.au.dk/fmiutils/fmuanalyzer.

I will propose some text, and then I hope that you @clagms  will go over it :)
The text should probably also contain some details on how to interpret the results.

I will take care of putting it on the website once we have some text that we agree to.

**Comment by CThuleHansen** [comment]
Proposed text: 

The FMI specification is semi-formal and allows for different interpretations, which lead to different implementations of FMUs. The FMU Analyzer is a tool that tests the dynamic behaviour of an FMU by executing functions of the FMU.

The tool is based on Model-Based Testing for evaluation, which has the benefit that the model used to describe the possible behaviours of an FMU can also be used to test it. The source code is available at: https://msdl.uantwerpen.be/git/claudio/FMIMOBSTER

If you disagree with a checking result then we are very interested in hearing about it!
It will allow us to pin down a more accurate interpretation of the standard, and (possibly) correct issues in the tools. Please report issues here: https://msdl.uantwerpen.be/git/claudio/FMIMOBSTER/issues

This approach is also presented in the article **TODO: REF PUBLICATION**

The parameter n is ... **TODO: DESCRIBE**
The parameter l is ... **TODO: DESCRIBE**

The results.zip contains the following **TODO: DESCRIBE**

**Comment by clagms** [comment]
Here's an extension of the above.
If approved, can you put it in the website @CThuleHansen ?

> The FMI specification is semi-formal and allows for different interpretations, which lead to different implementations of FMUs.
> We recognize that it is  difficult to rigorously specify a standard to the level required by automated synthesis.
> Hence, we propose the FMIMOBSTER, which uses model based testing for the evaluation of FMUs.
> This has the benefit that the model used to describe the possible behaviors of an FMU can also be used to test it, and the tool can be applied with minimal setup and know-how.
> 
> If you disagree with a checking result then we are very interested in hearing about it!
> It will allow us to pin down a more accurate interpretation of the standard, and (possibly) correct issues in the tools. Please report issues here: https://msdl.uantwerpen.be/git/claudio/FMIMOBSTER/issues
> The parameters and results used in this website are detailed in the documentation: 
https://msdl.uantwerpen.be/git/claudio/FMIMOBSTER/#running-an-example-and-general-workflow

**Comment by clagms** [comment]
I haven't put a ref to the article yet because nobody has access to it anyhow. It's submitted.
Once we know the submission outcome, we can think about this.

**Comment by clagms** [comment]
Maybe add the following, for a quick demo example:

For a quick tryout of the tool,
1. Download the watertank FMU from [here](https://msdl.uantwerpen.be/git/claudio/FMIMOBSTER/raw/master/src/test/resources/fmus/20-sim/threewatertank1.fmu).
2. Uploading to the tool, and press analyze.

**Comment by clagms** [comment]
We should add a small decription of the architecture in which the FMU runs.
If I understand correctly, the user has to upload an fmu that has been compiled to the right os/architecture, right?

**Comment by CThuleHansen** [comment]
Yes. Good idea with architecture. I Will add the text.
