### ISSUE TITLE
Add text to home 

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmi_utilities#12]
Add text to home describing the general fmi utilities idea.

**Comment by CThuleHansen** [comment]
We aim at supporting the community in rooting
out possible ambiguities and improving the conformance
to the standard. @clagms can I use this?

**Comment by clagms** [comment]
> We aim at supporting the community in rooting
> out possible ambiguities and improving the conformance
> to the standard. @clagms can I use this?

Perfect @CThuleHansen !

**Comment by CThuleHansen** [comment]
Fixed in https://github.com/INTO-CPS-Association/fmi_utilities/commit/9660335a8bfbef79a3eeb69d45f33096c0c77d81
