### ISSUE TITLE
"FMI Checker" failing for FmuExportCrossCompile.fmu

### ISSUE THREAD

**Issue by nickbattle** [INTO-CPS-Association/fmi_utilities#5]
Uploading fmi-cross-check-master/fmus/2.0/cs/arm-linux-gnueabi/OpenModelica/v1.11.0/FmuExportCrossCompile/FmuExportCrossCompile.fmu succeeds, but produces the error "BadStatus 413".

This might be because of the size of the FMU (2Mb)? Or it might be that the tool is only expecting to work with modelDescription.xml files, rather than FMUs.

(It really ought to work with FMU zip files. This is presumably the easiest way for people to submit their FMUs, and the FMU Analyser is the same?)

**Comment by CThuleHansen** [comment]
In case of fmichecker the modeldescription should be extracted on the client. No reason to send all that data to the server.

In case of fmu analyzer it already works with fmus, although I am rather surprised of the limit of 2Mb, thought I set it higher.. Will investigate.

**Comment by nickbattle** [comment]
I think we need to make this as easy as possible for people to use. Most FMUs are only a few hundred Kb. Those over 1Mb are rare. The largest I can see is 3.5Mb. So this won't take long to upload (seconds) and it is temporary data anyway. It would also be consistent if both tools took the same data.

If this is just an early release issue, that's fine. But I don't think we should release it more widely like this.

**Comment by CThuleHansen** [comment]
The release is an early release. And I do not disagree with you that it should be added. The rest was more a note to myself, that we might as well extract the modeldescription file before sending it to the server.

**Comment by CThuleHansen** [comment]
@nickbattle give it a go again. I am still correcting some things, but hopefully it roughly works now.

**Comment by nickbattle** [comment]
@CThuleHansen Yes, that works now:
```
2.2.8 InitialUnknowns must include: {3, 4}
false
```
Though that "false" makes me think that perhaps the VDMCheck you are using is older? The latest says "Errors found" (in the shell script)?

**Comment by CThuleHansen** [comment]
@nickbattle I was just about to open a issue on that :)
It is the old one.
Currently our CI is not set up for this, so I am doing it manually.

**Comment by CThuleHansen** [comment]
@nickbattle should be updated and up and running now. 
Cheers

**Comment by nickbattle** [comment]
Yes, that has been fixed...
```
2.2.8 InitialUnknowns must include: {3, 4}
Errors found. 
```
